# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180511_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
