# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180424_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModelManager',
        ),
    ]
